apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: custom-hpa-test-backendconfig
  namespace: custom-hpa-test
  labels:
    app: custom-hpa-test
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthcheck
    port: 80