apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: custom-hpa-test
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"80":"custom-hpa-test-backendconfig"}}'
  labels:
    app: custom-hpa-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: custom-hpa-test