apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: custom-hpa-test
  labels:
    app: custom-hpa-test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: custom-hpa-test