apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
  name: prometheus-kube-state-metrics
  namespace: monitoring
secrets:
- name: prometheus-kube-state-metrics-token-secret

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
  name: prometheus-kube-state-metrics-token-secret
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus-kube-state-metrics
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
  name: prometheus-alertmanager
  namespace: monitoring
secrets:
- name: prometheus-alertmanager-token-secret

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
  name: prometheus-alertmanager-token-secret
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus-alertmanager
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
  name: prometheus-node-exporter
  namespace: monitoring
secrets:
- name: prometheus-node-exporter-token-secret
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
  name: prometheus-node-exporter-token-secret
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus-node-exporter
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
  name: prometheus-pushgateway
  namespace: monitoring
secrets:
- name: prometheus-pushgateway-token-secret

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
  name: prometheus-pushgateway-token-secret
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus-pushgateway
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
  name: prometheus-server
  namespace: monitoring
secrets:
- name: prometheus-server-token-secret
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
  name: prometheus-server-token-secret
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus-server
type: kubernetes.io/service-account-token

